# Application Configuration
spring.application.name=restaurant-reservation

# --- H2 Configuration (Active) ---
# Datasource Configuration for H2 (Memory Database)
spring.datasource.url=jdbc:h2:mem:restaurant_db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# JPA Configuration for H2
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- PostgreSQL Configuration (Commented out) ---
# spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_db
# spring.datasource.username=postgres
# spring.datasource.password=student123
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Database Initialization

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:database/create.sql
spring.sql.init.data-locations=classpath:database/import.sql
spring.sql.init.continue-on-error=true

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Logimise tasemed
logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG
logging.level.org.springframework.jdbc=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.beans.factory=DEBUG
logging.level.org.springframework.context=DEBUG